<?php

namespace Database\Seeders;

use App\Models\Brand;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $brands = [
            [ 'name' => 'AEG' ],
            [ 'name' => 'Air France' ],
            [ 'name' => 'Acer' ],
            [ 'name' => 'Alcatel' ],
            [ 'name' => 'Alfa' ],
            [ 'name' => 'Amazon' ],
            [ 'name' => 'Amazfit' ],
            [ 'name' => 'Amica' ],
            [ 'name' => 'Anker' ],
            [ 'name' => 'AOC' ],
            [ 'name' => 'Apple' ],
            [ 'name' => 'Arcoslight' ],
            [ 'name' => 'Asus' ],
            [ 'name' => 'Audio-Technica' ],
            [ 'name' => 'Babyliss' ],
            [ 'name' => 'Balay' ],
            [ 'name' => 'Bang & Olufsen' ],
            [ 'name' => 'Bauknecht' ],
            [ 'name' => 'Belkin' ],
            [ 'name' => 'BenQ' ],
            [ 'name' => 'Bertazzoni' ],
            [ 'name' => 'Black & Decker' ],
            [ 'name' => 'Bissell' ],
            [ 'name' => 'Bosch' ],
            [ 'name' => 'Bose' ],
            [ 'name' => 'Braun' ],
            [ 'name' => 'Brother' ],
            [ 'name' => 'Bryton' ],
            [ 'name' => 'Budweiser' ],
            [ 'name' => 'Canon' ],
            [ 'name' => 'Carrier' ],
            [ 'name' => 'Casio' ],
            [ 'name' => 'Cata' ],
            [ 'name' => 'Cecotec' ],
            [ 'name' => 'Challenger' ],
            [ 'name' => 'Changhong' ],
            [ 'name' => 'Chefman' ],
            [ 'name' => 'Cisco' ],
            [ 'name' => 'Conair' ],
            [ 'name' => 'Concept' ],
            [ 'name' => 'Conceptronic' ],
            [ 'name' => 'Corsair' ],
            [ 'name' => 'CyberGhost VPN' ],
            [ 'name' => 'Daewoo' ],
            [ 'name' => 'D-Link' ],
            [ 'name' => 'Dell' ],
            [ 'name' => 'DeLonghi' ],
            [ 'name' => 'Denver Electronics' ],
            [ 'name' => 'Devolo' ],
            [ 'name' => 'Digitus' ],
            [ 'name' => 'DJI' ],
            [ 'name' => 'Dyson' ],
            [ 'name' => 'Edesa' ],
            [ 'name' => 'Elbe' ],
            [ 'name' => 'Electrolux' ],
            [ 'name' => 'Elica' ],
            [ 'name' => 'Emsa' ],
            [ 'name' => 'Energy Sistem' ],
            [ 'name' => 'Engel' ],
            [ 'name' => 'Epson' ],
            [ 'name' => 'Fagor' ],
            [ 'name' => 'Fitbit' ],
            [ 'name' => 'Fisher & Paykel' ],
            [ 'name' => 'Frigidaire' ],
            [ 'name' => 'Fujifilm' ],
            [ 'name' => 'Fujitsu' ],
            [ 'name' => 'Garmin' ],
            [ 'name' => 'Genius' ],
            [ 'name' => 'Gigabyte' ],
            [ 'name' => 'Gorenje' ],
            [ 'name' => 'Google' ],
            [ 'name' => 'Grundig' ],
            [ 'name' => 'Hama' ],
            [ 'name' => 'Haier' ],
            [ 'name' => 'Hanwha' ],
            [ 'name' => 'Harman Kardon' ],
            [ 'name' => 'Hasbro' ],
            [ 'name' => 'Haier' ],
            [ 'name' => 'HP' ],
            [ 'name' => 'Huawei' ],
            [ 'name' => 'iRobot' ],
            [ 'name' => 'Intel' ],
            [ 'name' => 'Ivacy VPN' ],
            [ 'name' => 'Jabra' ],
            [ 'name' => 'JVC' ],
            [ 'name' => 'Jiso' ],
            [ 'name' => 'Kenwood' ],
            [ 'name' => 'KitchenAid' ],
            [ 'name' => 'Kodak' ],
            [ 'name' => 'LG' ],
            [ 'name' => 'Lenovo' ],
            [ 'name' => 'Lexmark' ],
            [ 'name' => 'Liebherr' ],
            [ 'name' => 'Logitech' ],
            [ 'name' => 'Longhi' ],
            [ 'name' => 'Magimix' ],
            [ 'name' => 'Makita' ],
            [ 'name' => 'Manta' ],
            [ 'name' => 'Marshall' ],
            [ 'name' => 'MasterChef' ],
            [ 'name' => 'Matsui' ],
            [ 'name' => 'Media Markt' ],
            [ 'name' => 'Medion' ],
            [ 'name' => 'Meizu' ],
            [ 'name' => 'Miele' ],
            [ 'name' => 'Microsoft' ],
            [ 'name' => 'Mini Cooper' ],
            [ 'name' => 'Miniso' ],
            [ 'name' => 'Mitre' ],
            [ 'name' => 'Mitsubishi' ],
            [ 'name' => 'Midea' ],
            [ 'name' => 'Moleskine' ],
            [ 'name' => 'Monacor' ],
            [ 'name' => 'Motorola' ],
            [ 'name' => 'Moulinex' ],
            [ 'name' => 'NEC' ],
            [ 'name' => 'Nespresso' ],
            [ 'name' => 'Netgear' ],
            [ 'name' => 'Nikon' ],
            [ 'name' => 'Nintendo' ],
            [ 'name' => 'Nissan' ],
            [ 'name' => 'Nokia' ],
            [ 'name' => 'Nordmende' ],
            [ 'name' => 'Nutribullet' ],
            [ 'name' => 'Olympus' ],
            [ 'name' => 'OSRAM' ],
            [ 'name' => 'Oster' ],
            [ 'name' => 'Panasonic' ],
            [ 'name' => 'Pantum' ],
            [ 'name' => 'Philips' ],
            [ 'name' => 'Pioneer' ],
            [ 'name' => 'Polaroid' ],
            [ 'name' => 'Powermatic' ],
            [ 'name' => 'Proscenic' ],
            [ 'name' => 'RadioShack' ],
            [ 'name' => 'Ray-Ban' ],
            [ 'name' => 'Real Madrid' ],
            [ 'name' => 'Realme' ],
            [ 'name' => 'Red Bull' ],
            [ 'name' => 'Redmi' ],
            [ 'name' => 'Remington' ],
            [ 'name' => 'Reo' ],
            [ 'name' => 'Ricoh' ],
            [ 'name' => 'Rival' ],
            [ 'name' => 'Roborock' ],
            [ 'name' => 'Roku' ],
            [ 'name' => 'Rowenta' ],
            [ 'name' => 'Royal Philips' ],
            [ 'name' => 'Samsung' ],
            [ 'name' => 'Sandisk' ],
            [ 'name' => 'Sanyo' ],
            [ 'name' => 'Schneider' ],
            [ 'name' => 'Securitas Direct' ],
            [ 'name' => 'Segway' ],
            [ 'name' => 'Seiko' ],
            [ 'name' => 'Sharp' ],
            [ 'name' => 'Siemens' ],
            [ 'name' => 'Singer' ],
            [ 'name' => 'SiriusXM' ],
            [ 'name' => 'Skoda' ],
            [ 'name' => 'Skyworth' ],
            [ 'name' => 'Smartmi' ],
            [ 'name' => 'Smeg' ],
            [ 'name' => 'Sony' ],
            [ 'name' => 'SoundPEATS' ],
            [ 'name' => 'Spectre' ],
            [ 'name' => 'Spotify' ],
            [ 'name' => 'Square Enix' ],
            [ 'name' => 'Staples' ],
            [ 'name' => 'Starrett' ],
            [ 'name' => 'SteelSeries' ],
            [ 'name' => 'Stihl' ],
            [ 'name' => 'Sub-Zero' ],
            [ 'name' => 'Sunbeam' ],
            [ 'name' => 'Supercell' ],
            [ 'name' => 'Supra' ],
            [ 'name' => 'TCL' ],
            [ 'name' => 'Technics' ],
            [ 'name' => 'Tefal' ],
            [ 'name' => 'Tesla' ],
            [ 'name' => 'Thomson' ],
            [ 'name' => 'Toshiba' ],
            [ 'name' => 'Toyota' ],
            [ 'name' => 'TP-Link' ],
            [ 'name' => 'Trek' ],
            [ 'name' => 'Uniden' ],
            [ 'name' => 'Uniqlo' ],
            [ 'name' => 'V-Moda' ],
            [ 'name' => 'Vizio' ],
            [ 'name' => 'Volkswagen' ],
            [ 'name' => 'Wahl' ],
            [ 'name' => 'Walmart' ],
            [ 'name' => 'Waring' ],
            [ 'name' => 'Whirlpool' ],
            [ 'name' => 'Xiaomi' ],
            [ 'name' => 'Yamaha' ],
            [ 'name' => 'Yale' ],
            [ 'name' => 'Yeedi' ],
            [ 'name' => 'Yuneec' ],
            [ 'name' => 'Zebra' ],
            [ 'name' => 'Zehnder' ],
            [ 'name' => 'Zanussi' ],
            [ 'name' => 'ZTE' ],
        ];

        foreach ($brands as $brand) {
            Brand::create($brand);
        }
    }
}
